### ISSUE TITLE
Feature idea: fully automatic printing

### ISSUE THREAD

**Issue by JasonTable** [aleksilassila/litematica-printer#100]
Basically makes the player fly around to areas that need printing. Could work somewhat like a 3D printer does in real life. Go layer by layer starting from the bottom make the player fly around placing blocks below him. Placing them in mid air if he needs to. and once a layer is done, move on to the next layer until the model is finished.

i don't think any complex path finding would be needed or anything. it just has to move Steve to be right above where the block goes and place it below him. then move to be above where the next block goes. just has to be careful not to make him move too fast.

**Comment by TechnoCoder08** [comment]
Baritone mod can be used to place schematics

**Comment by lil-peener** [comment]
> Baritone mod can be used to place schematics

baritone is not compatible with litematica

**Comment by JasonTable** [comment]
Baritone is also meant only for survival mode. It cannot make you fly around and cannot put building blocks into the hotbar automatically.

**Comment by aleksilassila** [comment]
This is out of the scope of the project at the time being. Baritone probably does this far better than I could ever implement something similar.

**Comment by ytcyde** [comment]
How do we use baritone correctly with litematica?
