### ISSUE TITLE
blocks dont place on multiplayer

### ISSUE THREAD

**Issue by mikxd345** [aleksilassila/litematica-printer#102]
i tried printing in a build on a multiplayer server but the blocks dont place at all i mean they do but they just get put back into my inv and dont place

**Comment by alexvermaning0** [comment]
for me it does nothing i can toggle it on or off and press v whatever i want but does not place anything. it might be because there is water where another block needs to be. also on multiplayer

**Comment by aleksilassila** [comment]
Should be fixed in 3.0. Check your placement range if the issue persists, I would recommend setting it to 5.
