### ISSUE TITLE
update msg spam

### ISSUE THREAD

**Issue by acaciachan** [aleksilassila/litematica-printer#106]
![image](https://user-images.githubusercontent.com/73088428/173499675-3190a4ee-270a-4b1e-8737-b7402e8bc4cd.png)

**Comment by acaciachan** [comment]
and i had already updated to 2.4, but it still here

**Comment by TechnoCoder08** [comment]
I have the same problem

**Comment by aleksilassila** [comment]
What version of Minecraft is this

**Comment by TechnoCoder08** [comment]
1.18.1

**Comment by otoara** [comment]
Experiencing this after updating to 2.4 on 1.19 a few minutes ago. particularly spams it when i go into free cam

**Comment by aleksilassila** [comment]
I'll be releasing 2.5 in a moment, please reopen this issue if it still persists there. If it does, let me know what mods you are using. I'm having hard time reproducing this.
