### ISSUE TITLE
incompatible mod set 1.18.2

### ISSUE THREAD

**Issue by celestials24** [aleksilassila/litematica-printer#107]
Hello I installed the latest version of the mods but when launching the game I have this error message

Error message : 

Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
Install fabric, any version.
Unmet dependency listing:
Mod 'Litematica Printer' (litematica_printer) 2.4 requires any version of fabric, which is missing!

screen :
[https://zupimages.net/up/22/24/lm46.png](url)
[https://zupimages.net/up/22/24/t8o5.png](url)

thank you in advance

**Comment by white-devil42** [comment]
did you install fabric api

**Comment by aleksilassila** [comment]
Yep, @celestials24 you're missing fabric api or some other dependency, see the downloads page for all dependencies
