### ISSUE TITLE
Compatability with the 1.19 community port?

### ISSUE THREAD

**Issue by The-Noble** [aleksilassila/litematica-printer#109]
If you haven't already heard there was a community port of all of masa's mods, including litematica. Untill the full recode of masa's mods, I love to see compatibility with these versions. 

They can be found here https://kosma.pl/masamods/

**Comment by warmbroke** [comment]
A working version:
`git clone https://github.com/warmbroke/litematica-printer`
go into the `litematica-printer` dir and make a directory named `prebuilt`, put [litematica-fabric-1.19-0.11.3.jar](https://kosma.pl/masamods/litematica-fabric-1.19-0.11.3.jar) and [malilib-fabric-1.19-0.12.1.jar](https://kosma.pl/masamods/malilib-fabric-1.19-0.12.1.jar) into the `prebuilt` dir, then run `./gradlew build`.

**Comment by maplepy** [comment]
> for anyone who would like a prebuilt jar: [litematica-printer-1.19-2.4.jar.zip](https://github.com/aleksilassila/litematica-printer/files/8947123/litematica-printer-1.19-2.4.jar.zip)

doesn't seem to be working for me, can't even find the settings in the litematica settings

**Comment by TheVigilantWolf** [comment]
Thanks @warmbroke that worked wonderfully.

**Comment by kwill5800** [comment]
^

**Comment by Ghozgul** [comment]
Mine doesn't work, it non stop place blocks when I'm close to the schematics even if the printer is turned off. Also it doesn't applies rotation like previous version were doing...

**Comment by maplepy** [comment]
Can we maybe stop sending replies?

We have established that it worked and the 

> ^

or other comments like that are unnecessarily spamming the opened issue.

Leaving a like on the comment is enough to know if it works or not thanks

**Comment by kwill5800** [comment]
> Can we maybe stop sending replies?
> 
> We have established that it worked and the
> 
> > ^
> 
> or other comments like that are unnecessarily spamming the opened issue.
> 
> Leaving a like on the comment is enough to know if it works or not thanks

very cool

**Comment by aleksilassila** [comment]
> A working version: `git clone https://github.com/warmbroke/litematica-printer` go into the `litematica-printer` dir and make a directory named `prebuilt`, put [litematica-fabric-1.19-0.11.3.jar](https://kosma.pl/masamods/litematica-fabric-1.19-0.11.3.jar) and [malilib-fabric-1.19-0.12.1.jar](https://kosma.pl/masamods/malilib-fabric-1.19-0.12.1.jar) into the `prebuilt` dir, then run `./gradlew build`.
> 
> for anyone who would like a prebuilt jar: [litematica-printer-1.19-2.4.jar.zip](https://github.com/aleksilassila/litematica-printer/files/8947123/litematica-printer-1.19-2.4.jar.zip)

Good job, would you mind if I included your jar in my releases until masa gets 1.19 done and adds the versions to his maven repo? Don't feel like writing a dirty fix in the meantime, especially if you already beat me to it :)

**Comment by warmbroke** [comment]
> > A working version: `git clone https://github.com/warmbroke/litematica-printer` go into the `litematica-printer` dir and make a directory named `prebuilt`, put [litematica-fabric-1.19-0.11.3.jar](https://kosma.pl/masamods/litematica-fabric-1.19-0.11.3.jar) and [malilib-fabric-1.19-0.12.1.jar](https://kosma.pl/masamods/malilib-fabric-1.19-0.12.1.jar) into the `prebuilt` dir, then run `./gradlew build`.
> > for anyone who would like a prebuilt jar: [litematica-printer-1.19-2.4.jar.zip](https://github.com/aleksilassila/litematica-printer/files/8947123/litematica-printer-1.19-2.4.jar.zip)
> 
> Good job, would you mind if I included your jar in my releases until masa gets 1.19 done and adds the versions to his maven repo? Don't feel like writing a dirty fix in the meantime, especially if you already beat me to it :)

Totally fine with that.

**Comment by Qwaentos** [comment]
I've noticed that the placement speed in the 1.19 version of printer is locked to above 2, while in the past it was possible to just input the value as low as you'd like, resulting in much faster printing. Is this done on purpose? And will the quicker printing get added again in the future?

**Comment by maplepy** [comment]
Hey is there a version you know of for 1.19.1 ? or maybe this is already being built?

**Comment by warmbroke** [comment]
1.19 to 1.19.1 is pretty straightforward, there are almost no changes.
malilib: https://github.com/warmbroke/malilib/releases/tag/a577b6e
litematica: https://github.com/warmbroke/litematica/releases/tag/230539b
prebuilt printer: https://github.com/warmbroke/litematica-printer/releases/tag/e3070eb
