### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by basvlier** [aleksilassila/litematica-printer#11]
hey,

maby a good idea tho put a small tutorial where you put the files bcs I have no idea

**Comment by aleksilassila** [comment]
Instead of commenting on every issue there is in this repo, go see a tutorial in youtube on how to use fabric mods in general. This mod is no exception.

**Comment by basvlier** [comment]
Im sorry I dint read it

Op do 11 mrt. 2021 om 23:26 schreef Aleksi Lassila ***@***.***

**Comment by basvlier** [comment]
But It isnt an .jar file do I need to put the whole folder in the mod
thingie

Op do 11 mrt. 2021 om 23:26 schreef Aleksi Lassila ***@***.***

**Comment by basvlier** [comment]
- Run gradlew build to build the mod
   - The built jar file will be inside build/libs/
   - IDK what you need to do whit this pls help
   - greetings from holland!


Op do 11 mrt. 2021 om 23:26 schreef Aleksi Lassila ***@***.***

**Comment by aleksilassila** [comment]
You don't need to clone the project nor build it, just download the jar from releases https://github.com/aleksilassila/litematica-printer/releases

**Comment by basvlier** [comment]
Awesome, thanks!

Op zo 14 mrt. 2021 om 09:07 schreef Aleksi Lassila ***@***.***
