### ISSUE TITLE
Blocks dissapearing

### ISSUE THREAD

**Issue by Reesedoesgaming** [aleksilassila/litematica-printer#111]
I use this in a multiplayer server, and whenever it places blocks, it would place but when you leave some of the blocks aren't actually placed and some disappear, making the build look like swiss cheese, with holes and not complete

**Comment by aleksilassila** [comment]
This is because the server seems the placements invalid. This might happen if your printing range or speed is too high, or if your server has some kind of anticheat. I'd start with reducing the placement range though.
