### ISSUE TITLE
Post to CurseForge or Modrinth?

### ISSUE THREAD

**Issue by RandomGgames** [aleksilassila/litematica-printer#113]
Would it be possible to upload this mod to CurseForge or Modrinth?

**Comment by aleksilassila** [comment]
Is there some kind of benefits from doing that? Seems like just extra work

**Comment by aleksilassila** [comment]
Okay, haven't used mod managers myself but that is a good point. I should look into it next time I do a release

**Comment by RandomGgames** [comment]
Hey! You've posted a few releases but still haven't seen anything on any other websites. Still think you could do this?
Maybe I could help out and keep a Modrinth page updated for you if you're interested?

**Comment by aleksilassila** [comment]
Still planning on putting it on curseforge, but feel free to create a Modrinth for the project since I don't see myself updating the mod in more websites than github and curseforge.

**Comment by aleksilassila** [comment]
👍 Thanks for maintaining this. Will close the issue

**Comment by RandomGgames** [comment]
Hey! It's been a while since I've asked you about allowing me to do this. Since then, I have actually accumulated some earning through the posting. I haven't touched it yet, but I don't feel right just taking them without consulting you since you created the mod. Maybe we can discuss what to do with it? Otherwise for now I will leave it and let it grow.

**Comment by aleksilassila** [comment]
If it's just small amounts, you can keep all of it 👍

**Comment by RandomGgames** [comment]
Thanks! Yeah it's only like $9 :P

**Comment by burpotato** [comment]
@RandomGgames a temporary version for 1.21 is up on the github

**Comment by RandomGgames** [comment]
@burpotato Added

**Comment by aleksilassila** [comment]
@RandomGgames I was wondering how much money is the project generating via the modrinth revenue share? Was surprised by how many downloads it has

**Comment by RandomGgames** [comment]
I told you posting on Modrinth was a good idea! :D

This is the only project I’ve helped manage so that makes figuring out the revenue easy. As of 3 minutes ago when I checked, there’s $138.42 available to be withdrawn, and more pending from the last few months that cannot be taken yet. This is the amount from the very beginning, as I haven’t withdrawn anything since I created the modrinth page, and still haven’t.

**Comment by RandomGgames** [comment]
@aleksilassila Do you take donations?

**Comment by aleksilassila** [comment]
👋

**Comment by AncientZerox** [comment]
TF you mean modrinth Pays you ?? My mod has like 39k downloads i don't get paid
