### ISSUE TITLE
Double slabs cannot be placed correctly sometimes!!!

### ISSUE THREAD

**Issue by wjwpli** [aleksilassila/litematica-printer#115]
printer version:2.4
minecraft version:1.19
multiplayer server:paper
litematic version:0.11.3
fabric api version:0.58.0
fabric version:0.14.8
no mod crash with the printer,and i havent seen such bug in printer version below 2.1,
the double slabs would be placed like this sometimes:
<img width="1280" alt="Desktop Screenshot 2022 07 30 - 12 24 51 77" src="https://user-images.githubusercontent.com/64727603/181872258-b9e547f4-ff57-4ec7-bb17-3e4afcaa6948.png">
and when i quit the game and then join again,it would be ok sometimes,or still have such issue.
fix it please~

**Comment by aleksilassila** [comment]
Let me know if the issue persists in 3.0
