### ISSUE TITLE
Double Slab placing

### ISSUE THREAD

**Issue by DereC4** [aleksilassila/litematica-printer#12]
**Minecraft version**
1.16.5

**Mod version and malilib version**

malilib-fabric-1.16.4-0.10.0-dev.21+arne.2.jar

Printer version: 1.6

**Description of the bug**
Double slabs are interpreted as single slabs for some reason

**Expected behavior** (if not clear from the description)

It would auto "fill" the slab by placing two slabs inside the block to create a double slab. Instead, a single bottom type slab is placed. 

**To Reproduce** (if not clear from the description already)
1. Load a schematic with double slabs
2. Turn on printer
3. Printer only places down single slabs, not the full slab

**Screenshots**
https://i.imgur.com/UAc0fz4.png

**Additional context**
Nothing else

**Comment by aleksilassila** [comment]
Will be fixed in the next release

**Comment by DereC4** [comment]
Thanks
