### ISSUE TITLE
Version 2.5 CTD's on launch

### ISSUE THREAD

**Issue by otoara** [aleksilassila/litematica-printer#121]
https://pastebin.com/sqsP9JfL

Just updated to 2.5 and game crashes to desktop as soon as it is launched, i have attatched my log via the pastebin link.

Does this with my other mods (here --> https://imgur.com/a/j4auXZB )
And with only litematica and malilib installed

**Comment by ThebestkillerTBK** [comment]
I think removing the update detector can be great

**Comment by ThebestkillerTBK** [comment]
#120

**Comment by otoara** [comment]
> #120
Thanks i'll try that
