### ISSUE TITLE
Can`t run game after adding mod

### ISSUE THREAD

**Issue by adrianek320** [aleksilassila/litematica-printer#123]
logs: https://pastebin.com/kg9umYzR
launcher: Feather Fabric 1.17.1

**Comment by adrianek320** [comment]
Only I use 1.17.1 and that is on 1.19.2

**Comment by kaisomir** [comment]
apologies, just copypasted - i'll see if I can fix it for 1.17.1 too :)

**Comment by kaisomir** [comment]
Just compiled and tested this, appears to be the same issue as 1.19 - let me know if it works (or doesn't) <3

[litematica-printer-1.17.1-2.5.zip](https://github.com/aleksilassila/litematica-printer/files/9302221/litematica-printer-1.17.1-2.5.zip)

**Comment by adrianek320** [comment]
Works, thanks <3

**Comment by aleksilassila** [comment]
Yep it's the same issue on every version, but it's fixed now also in the releases. Didn't bother to make a new version, just redownload 2.5. Let me know if there are other issues and thans @kaisomir for patching this early
