### ISSUE TITLE
Rails, redstone torches, observers and pistons are placed wrong

### ISSUE THREAD

**Issue by Mednaceex** [aleksilassila/litematica-printer#124]
Pistons and observers are sometimes (like 30% of the time) placed facing the wrong direction, and redstone torches are always placed as wall torches if there is a solid block next to them, even if they should be attach to the ground. Also rails are placed according to the player's position and if there is a single piece of rail it doesn't get rotated into the correct position.

**Comment by aleksilassila** [comment]
I'll look into that. In the meantime, it would be helpful if you were able to figure out how to reliably reproduce the piston issue. If it happens randomly when you don't change the target block that is printed to, try to lower the printing speed and see if you can still reproduce the issue

**Comment by Mednaceex** [comment]
Alright, I'll try to investigate this problem soon

**Comment by aleksilassila** [comment]
Should be fixed in 3.0
