### ISSUE TITLE
1.19.2 Cannot Print Underwater (replacefluid does not work)

### ISSUE THREAD

**Issue by Johnyisgay1999** [aleksilassila/litematica-printer#129]
Hi, the Replace Fluid option does not work in 1.19.2. Printing does not work underwater this option should toggle this but in this version it does not work, hope to hear a reply thanks.

**Comment by victore99fna** [comment]
https://github.com/aleksilassila/litematica-printer/issues/134

**Comment by aleksilassila** [comment]
3.0
