### ISSUE TITLE
the printer does not select blocks 2.5/1.19.2

### ISSUE THREAD

**Issue by swiblik** [aleksilassila/litematica-printer#130]
Hi, maybe I have a stupid problem. The printer does not want to choose the blocks from the inventory itself, I have to do it myself. Also, if I take any other block, it puts it exactly. Help me fix this, please.

https://www.youtube.com/watch?v=XFrExMJVu8w

**Comment by Glitch4556** [comment]
I have the exact same issue, I would like a fix aswell

**Comment by aleksilassila** [comment]
Hopefully this has been fixed in 3.0. Reopen if the issue still persists after updating.
