### ISSUE TITLE
Observer facing direction

### ISSUE THREAD

**Issue by LuckiestOne23** [aleksilassila/litematica-printer#132]
Observer are not facing properly on placement. While I at first thought their alignment was completely random or according to the relative position towards the player (facing as they would on normal placement), it is not. The facing direction is appears to be simply the exact opposite, turned by 180 degree to be more precise. Instead of facing north it's south, top vs bottom, you get the idea.
After building countless redstone machines and having to replace every single observer by hand, I'd like to finally address this issue. I would be glad if you could provide any starting point for my journey on how to fix this, e.g. what methods I should precisely take a look at.

**Comment by LuckiestOne23** [comment]
Figured I was just using version 2.1. Sry for bothering

**Comment by white-devil42** [comment]
i was wondering how it could happen, it was fixed a long time ago
