### ISSUE TITLE
Vulcan Unfair Advantage

### ISSUE THREAD

**Issue by Blockbuster-MC** [aleksilassila/litematica-printer#136]
any idea what is causing me to get kicked when using the printer.  it is allowed on the server, however, i get Vulcan Unfair Advantage when using the printer and it kicks me.  

Any idea what needs to be changed on my end or the server end?

**Comment by aleksilassila** [comment]
Sounds like the anti cheat detects that the printer is trying to place blocks without looking or without clear line of sight. I'm afraid the only fix to this is to disable the anti cheat, or make changes to how the printer works.
