### ISSUE TITLE
Unable to start with mod installed

### ISSUE THREAD

**Issue by mapotter** [aleksilassila/litematica-printer#137]
Every since updating to Minecraft 1.19.2 I've been unable to use Litematica Printer, the latest version 2.5 is installed, and will always exit with 'code 1 (0x1) I've tried updating all versions of other mods, and the Fabric API version, and tried removing all other mods besides the ones required to use this and always the same result. 

Attached is the log from MultiMC with the mod enabled. This one has others also, but I did try with only the required and same results. 

[Litematica Printer 2.5 error.txt](https://github.com/aleksilassila/litematica-printer/files/9710427/Litematica.Printer.2.5.error.txt)

**Comment by aleksilassila** [comment]
Could not reproduce. Double check if the following:
  - You actually have the latest 2.5 version. Redownload the mod from releases.
  - You can produce the same error with vanilla launcher.

If the issue still persists, please reopen this issue.
