### ISSUE TITLE
Axe stripping not working

### ISSUE THREAD

**Issue by Guty18** [aleksilassila/litematica-printer#140]
Hi, I'm using linematica printer version 2.5 for 1.19.2 with linematica main mod in version 0.12.5 and the axe striping feature is not working, I have the axe in my Hotbar and even if it places the log correctly it doesn't strip them.

P.S: I have the axe striping option enabled in the configs.

 Thanks

**Comment by aleksilassila** [comment]
The whole printer has been rewritten in 3.0. Reopen if this issue persists in the latest version.
