### ISSUE TITLE
Mod version

### ISSUE THREAD

**Issue by arnokeesman** [aleksilassila/litematica-printer#143]
Mod version in `fabric.mod.json` is not changed from `${version}` to the actual version, in this case `3.0` during build.

**Comment by aleksilassila** [comment]
Indeed, that's an interesting find, will look for a solutin. Does it say ${version} when it's supposed to say 3.0 in mod menus or something, or how did you notice this?

**Comment by arnokeesman** [comment]
Noticed it while disabling the old version on the MultiMC modlist for my instance, it said `${` on `3.0` and `2.5` for `2.5`

**Comment by aleksilassila** [comment]
Oh okay, so this is a new one. Interesting

**Comment by aleksilassila** [comment]
This will be fixed in next update.
