### ISSUE TITLE
Issues with torches, walls and more since version 3.0

### ISSUE THREAD

**Issue by ampersandhd** [aleksilassila/litematica-printer#146]
The printer is not placing torches or walls automatically since updating to version 3.0 of the printer (using minecraft 1.19.2).

**Comment by aleksilassila** [comment]
Weird, it does in my test schematic. Do you a have a specific schematic that is incorrectly printer, that you could share?

**Comment by ampersandhd** [comment]
Did you use a litematic, a schem or a Schematic as base for your Printer?

**Comment by aleksilassila** [comment]
It's a .litematic file if that's what you mean

**Comment by ampersandhd** [comment]
I most times use schem files. I will go back to version 2.5 until this issue is fixed.

**Comment by aleksilassila** [comment]
Torches will be fixed in the next update.

**Comment by ampersandhd** [comment]
What about Walls, Dirt_Path and More?

**Comment by aleksilassila** [comment]
I fixed torches, note blocks and candles. If you know more blocks that are placed incorrectly, please make a list or give me a litematic file that is printed incorrectly so that I can look for the issues myself.
