### ISSUE TITLE
Printer occasionally places wrong block while in slow hover

### ISSUE THREAD

**Issue by usnavy2008** [aleksilassila/litematica-printer#150]
I play on a survival server that has a spell called carpet which lets us slowly hover in the air much like how you can in single player creative and you can move up/down and move forward/back. While placing blocks while moving in the air it occasionally places the wrong block of a build in the wrong spot. I probably am moving too fast for the printer?

**Comment by aleksilassila** [comment]
Does this only happen when you use the hover?

**Comment by usnavy2008** [comment]
yes i believe so

**Comment by aleksilassila** [comment]
Unfortunately any mod compatibility apart from anti-cheats is out of scope of this project since I don't have an easy way to debug mods and it would be too much work.
