### ISSUE TITLE
Lava is not replaced by the blocks

### ISSUE THREAD

**Issue by Antipartie** [aleksilassila/litematica-printer#16]
**Minecraft version**
1.6.5

**Mod version and malilib version**
malilib-fabric-1.16.4-0.10.0-dev.21+arne.2
litematica-fabric-1.16.3-1.6

**Description of the bug**
If there is lava on a surface, no block is placed. I turn on the printer and stand directly in front of the lava but it is not replaced.

**Expected behavior** (if not clear from the description)
Lava is replaced by the block to be placed in the blueprint

**To Reproduce** (if not clear from the description already)
Go underground at level 11, stand directly in front of the lava source and load a blueprint to replace the lava, e.g. a mining blueprint.

**Screenshots**
![2021-03-23_00 26 51](https://user-images.githubusercontent.com/81197319/112070624-5db8fd00-8b6e-11eb-9823-fcad9d9a33bb.png)

![2021-03-23_00 30 43](https://user-images.githubusercontent.com/81197319/112070841-d61fbe00-8b6e-11eb-8143-87f4bccf74bc.png)

**Additional context**
I hope the problem can be fixed  😉

**Comment by aleksilassila** [comment]
Will be fixed in the next patch
