### ISSUE TITLE
1.20

### ISSUE THREAD

**Issue by Andrew-Eathan** [aleksilassila/litematica-printer#176]
:)

**Comment by lightumcc** [comment]
the same feature request

**Comment by aleksilassila** [comment]
I try to get this out in the upcoming days

**Comment by JSOMaverick** [comment]
> I try to get this out in the upcoming days

Any update to this? hows development going for 1.20?

**Comment by lightumcc** [comment]
Although I am also looking forward to it, we should give developers enough time, especially for free plugins.

**Comment by wrl1224** [comment]
plz Update 1.20 ;)

**Comment by Belu97** [comment]
Plsss

**Comment by LittleKnightG** [comment]
any update?
