### ISSUE TITLE
Hello, Can u please release a 1.20.2 version please. And If So, Do you Have an Est date? Thanks

### ISSUE THREAD

**Issue by Appliedtrout** [aleksilassila/litematica-printer#191]
Hello, Can u please release a 1.20.2 version please. And If So, Do you Have an Est date? Thanks

**Comment by IlIlIlIIlIlIlIl** [comment]
> Hello, Can u please release a 1.20.2 version please. And If So, Do you Have an Est date? Thanks

https://github.com/aleksilassila/litematica-printer/releases/download/v3.2.1/litematica-printer-1.20.2-3.2.1.jar
