### ISSUE TITLE
Toggling Printer Crashes Game 1.20.4

### ISSUE THREAD

**Issue by CrazybobC** [aleksilassila/litematica-printer#198]
When using litematica-printer-fabric-3.2.1 for 1.20.x on Minecraft version 1.20.4, the game launches and runs just fine, however when toggling the printer and getting in range of a loaded schematic the game crashes. I'm not sure if I missed something and this version of printer is incompatible with 1.20.4, or if something is wrong. This happens on both single player and multiplayer. If this isn't an issue and I'm just using an incompatible version, please let me know, and if it is an issue I'd be more than willing to supply crash logs, if you can tell me what you need from them.

**Comment by aleksilassila** [comment]
I've added 1.20.4 build here https://github.com/aleksilassila/litematica-printer/releases/tag/v3.2.1, reopen if still persists

**Comment by Sofian2002** [comment]
I cant print when i press the hotkey
