### ISSUE TITLE
ghost blocks

### ISSUE THREAD

**Issue by FredTheFriendlyFox** [aleksilassila/litematica-printer#20]
**NOTE**:
* Before reporting an issue, please make sure it has not already been fixed in a later version! Also make sure you have the latest version of **both Litematica and malilib!** There are occasionally changes that **will require** both mods to be updated at the same time, or something will break! The very latest development versions are available here: https://masa.dy.fi/mcmods/client_mods/ so you can quickly check if you have the latest builds. The versions on CurseForge are not usually the very latest builds, but important bugfixes will also be uploaded there.
* Please don't post simple questions like "How do I do X?" on this issue tracker. Such help requests should happen on Discord instead: https://discord.gg/VNVG3Wk (or if the previous link is broken: https://discord.gg/scicraft -> `#masas-mods`)
* Don't post issues for mod versions made for Minecraft snapshots on this tracker. The snapshot versions aren't "properly" supported or tested, they are provided as quick ports (when I have the time to make them) in a "might work, mostly" basis, and those issues should rather be handled on Discord as well.

**Minecraft version**
Which Minecraft version are you playing on?

**Mod version and malilib version**
Which **exact** mod version are you using? Include the **full** mod file name which includes the build date and time for the development versions, or you can see the mod version in the title of the Litematica main menu.
**"Latest" is not a version!!** It's ambiguous, it's a moving target, and very often the version is not *actually* even the latest available version at that time.

**Description of the bug**

---

You can remove this and all the following non-applicable sections of this template (and the first paragraph notice)!

---

**Expected behavior** (if not clear from the description)

**To Reproduce** (if not clear from the description already)
2. Do X '....'
3. See error

**Screenshots**

**Additional context**

**Comment by FredTheFriendlyFox** [comment]
just for context i build on a server witch im op on but i have to build in solo world first i copy the schem and paste it, after i activate the printer upon using it the printing was very slow so i turned the speed up to 0.05 and it placed them fast but when quitting and joining to see if it placed ghost block i found that the whole section i did had ghost blocks some were placed but the majority were ghost blocks. is this because of the mod or is it simply the server doing this because it cant keep up?

**Comment by DarkReaper231** [comment]
That's problem with server it self. You won't be able to fix that. Just use slower speed.

**Comment by aleksilassila** [comment]
Yeah, lower the speed and/or printing range, the server might also mark some placements as invalid if you are trying to place too far.
