### ISSUE TITLE
How to run in 1.21?

### ISSUE THREAD

**Issue by basil222** [aleksilassila/litematica-printer#223]
I can't find litematica 1.21 but this mod is updated to 1.21...
How can i run it in 1.21?

**Comment by ct1735x** [comment]
Please note that neither this mod or the Litematica mod are updated to 1.21

**Comment by Tom1817** [comment]
Hi, as per this reddit post

https://www.reddit.com/r/litematica/comments/1di4o3h/announcement_about_litematicas_future_and_updates/

Litematica has been ported to 1.21 : https://github.com/sakura-ryoko/litematica/releases/
and Malilib: https://github.com/sakura-ryoko/malilib/releases/

Just in case it's not known - these are now available :)

**Comment by ct1735x** [comment]
Oh that’s good to know, thanks! Let’s wait for the printer now 😄

**Comment by Tom1817** [comment]
@aleksilassila any update please? :)

**Comment by aleksilassila** [comment]
1.21 version added here https://github.com/aleksilassila/litematica-printer/releases/tag/v3.2.1
