### ISSUE TITLE
please update for 1.17

### ISSUE THREAD

**Issue by ImLorio** [aleksilassila/litematica-printer#23]
please update for 1.17

**Comment by FelipeAzambuja** [comment]
please update

**Comment by Kumicoo** [comment]
pleassse update

**Comment by ForBai** [comment]
pls

**Comment by aleksilassila** [comment]
Unfortunately I wont be able to work with any of my projects for at least the following 2 weeks, I'll try to catch up with this after that. No promises though

**Comment by pofdzm** [comment]
good luck!

**Comment by DereC4** [comment]
I think we should have patience as this is a dev's independent project they most likely did for the community. We really appreciate your work!

**Comment by DereC4** [comment]
Yay it's out guys
