### ISSUE TITLE
Crash when joining server

### ISSUE THREAD

**Issue by emielderckx** [aleksilassila/litematica-printer#27]
**Minecraft version**
1.17.1

**Mod version and malilib version**
litematica-fabric-1.17.1-0.0.0-dev.20210713.103711
malilib-fabric-1.17.1-0.10.0-dev.24
litematica-printer-1.17-1.8

**Description of the bug**
Startup join a server and crash

**Screenshots/paste**
https://mcpaste.io/0ba68bec22526b4a
![image](https://user-images.githubusercontent.com/35953244/127899699-b6fc52db-fa1b-4236-9f3e-1bce239638e6.png)

**Comment by aleksilassila** [comment]
Reopen if persists in the latest version
