### ISSUE TITLE
How to Use/Control

### ISSUE THREAD

**Issue by Nightcore0302** [aleksilassila/litematica-printer#28]
Soooo

I've got a problem with this modification. First of all is there any kind of Explanation anywhere other than in-game Controls? like a Readme that says how to find the Configurations of Litematica Printer or which one is for the mod and not for the normal Litematica? The only one I've found on Github was the Read.me About the Project, But not how to use it.

I can't seem to find a way to get it to work because I don't really know where it is. So maybe it would be nice to know which Keybind is used For the Printer or an Overview on how to set up the Mod.

AND LASTLY
 I'm sorry if I'm using the Platform wrong the only reason I've used it so far was to find and Info about Paper and this Problem of mine with the Mod. So don't know if what I'm doing is right if not please correct me.

I Hope for a response and wish yall a Wonderful day!

**Comment by aleksilassila** [comment]
Hey,

That's a good point, I probably should add a quick tutorial on how to use the mod. For now though, you'll find all the printer settings at the bottom of literates settings tab (M + C), there you can manage printing speed and range etc. There's also an option to set the printer's hotkey in litematica's hotkeys tab. By default you can toggle the printer on and off by pressing M + O.

If you don't know how to use plain litematica, there are YouTube videos online to show you the basics, start with those. 

Cheers
