### ISSUE TITLE
Unnecessary save folder bundled with the .jar release files

### ISSUE THREAD

**Issue by CommandPromptGamer** [aleksilassila/litematica-printer#29]
**Minecraft version:** 1.17.1 (irrelevant as it is on the release files themselves)

**Mod version and malilib version:** 1.8 and 1.17.1-0.10.0-dev.24 (again irrelevant)

**Description of the bug:** A seemingly useless save is bundled with both the 1.17 and 1.16 releases of the 1.8 version.

**Expected behavior:** The release files should have only the necessary files to run the mod and be a couple of kilobytes as the previous releases, not 7.14 MB because of a compressed 10.9 MB save folder that is a generic "New World" apparently used to test the mod judging by the cloned structures.

**To Reproduce:** 
1. Open one of the two 1.8 release files with a program that can unzip a. jar file, such as WinRAR, or simply change the file extension to .zip and open it with any zipping program.
2. Under the folder ```me``` there will be a save folder called ```aleksilassila``` you may copy this folder to your saves folder if you want to access it.
3. Delete this folder if you want to see how much the file shrinks without it.

**Screenshots:**

![Screenshot 2021-08-15 164616](https://user-images.githubusercontent.com/46406111/129490938-dc8c6fe7-d3a2-454a-a929-f9ff993afacf.png)
![2021-08-15_16 59 48 (Custom)](https://user-images.githubusercontent.com/46406111/129491544-48192aad-ae8f-4c10-9592-a3a7db8bcff3.png)

**Comment by aleksilassila** [comment]
Nice catch, didn't notice that. Will update the release files in a couple of weeks once I get home. 

Cheers
