### ISSUE TITLE
Litematica printer crashing minecraft

### ISSUE THREAD

**Issue by East1122** [aleksilassila/litematica-printer#3]
Im trying to install this "fork" but it keeps crashing minecraft. it could be because I'm playing on mac.

**Comment by aleksilassila** [comment]
What version of minecraft and fabric? What other mods do you have installed? What kind of error message do you get in minecraft launcher after the crash?

**Comment by East1122** [comment]
I used fabric 1.16.4. I have litematica and madlib and the printer installed. When it crashes it says “an unexpected issue occurred and the game has crashed. We’re sorry for the inconvenience. Exit code:0”

**Comment by aleksilassila** [comment]
Do you have both the fork and the original litematica installed?

**Comment by East1122** [comment]
Yes

**Comment by aleksilassila** [comment]
Install only the fork. No need for both. See if that fixes it

**Comment by aleksilassila** [comment]
Did you get it working? Can I close this?
