### ISSUE TITLE
The printer opens chests when trying to place blocks on them

### ISSUE THREAD

**Issue by demsarm** [aleksilassila/litematica-printer#30]
**Minecraft version**
1.16.4 (fabric loader 0.10.6 build 214

**Mod version and malilib version**
Which **exact** mod version are you using? - 
litematica-fabric-1.16.4-0.0.0-dev.20210612.170003.jar (What curseforge says it latest as of about 8 PM CET on the 18th of Aug. 2021)
malilib-fabric-1.16.4-0.10.0-dev.21+arne.5.jar (Same as with Litematica)

**Description of the bug**
The printer opens chests when placing blocks on and around chests, but I'm not sure why that would be). When attempting to close chest, it gets opened again, which makes any further progress difficult, as the only way to close the chest it through getting lucky and managing to disable the printer in the split second the UI isn't open after pressing Esc or E .After finally managing to exit the chest, you cannot move and are forced to relog. (After a while I figured out double-tapping Esc., going to another world and disabling the printer there is a much easier option).

**Expected behavior**
I expected the printer to place blocks(in my example chests(I had to place a row of 26 chests)) next to chests at least when sneaking, but I wouldn't have been surprised if the mod made me(my player) sneak.

**To Reproduce** (if not clear from the description already)
1. Tell the printer to place a row of chests, maybe only occurs when placing mid-air.
2. Get stuck in the chest GUI.
3. Get lucky and pause the printer right after closing GUI and before the printer opens it again.
4. Be unable to move.

**Additional context**
Notes: 
After a bit of messing around I managed to place multiple when sneaking but It opened the last chest in the line even when sneaking.
When I tried placing a chest on another chest it got opened(even when sneaking).
The bug probably happens with other blocks, that have a GUI, but i had enough of getting stuck in GUIs to test.
The printer still tries to place blocks when inside the UI

Edit: This only happens when placing chests, so a more appropriate title would be "Printer interacts with blocks when trying to place chests.

**Comment by maxsupermanhd** [comment]
Confirmed. @aleksilassila, any workaround?

**Comment by aleksilassila** [comment]
I'll try to get this fixed in next update. Might take a while though as I'm currently unavailable.

**Comment by maxsupermanhd** [comment]
Thank you.

**Comment by aleksilassila** [comment]
Haven't noticed this behavior in the latest version, reopen if the issue still persists
