### ISSUE TITLE
Disable placement of rotation dependant blocks until player is actually facing right direction

### ISSUE THREAD

**Issue by maxsupermanhd** [aleksilassila/litematica-printer#31]
I was using printer on server that checks facing of blocks and pistons, repeaters and all sorts of blocks were placed incorrectly. There should be option to disable placement of such blocks or just not placing them if player is facing wrong direction. On the particular server that I play on check is pretty simple and I think based on head/camera angle of a player that is placing block, so if I place block behind me it will face towards me just like I would place it in front of me (same for sides)

**Comment by aleksilassila** [comment]
I'll look into this when I get home. Do you know the plugin that does these facing checks?

**Comment by aleksilassila** [comment]
#71
