### ISSUE TITLE
Printer mode deleting false blocks

### ISSUE THREAD

**Issue by mcgodbuild** [aleksilassila/litematica-printer#32]
I am playing on a server and have creative mode. I like that litematica printer fork is updated for 1.17 which the server is on. 

In 1.12.2 schematica the printer function had an option to delete any block it deemed wrong. Very annoying with leaves and water but in general really helpful. I was reading in the summary of this litematica fork about deletion but I can't find any further info on it.

In case it's not already in the fork the way I would expect it, I would like the option to have the printer function be able to delete wrongfully placed blocks in creative mode. The original schematica had this function. I would expect as the same code was used, this would be possible right?

**Comment by aleksilassila** [comment]
This fork doesn't share any code with schematicas printer feature, so it would be quite a lot of work. Right now I unfortunately don't have time to add this, but maybe in the future :)
