### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by EduardoSepu** [aleksilassila/litematica-printer#34]
Hello, I like the idea of the printer, but I really dont know how to use it, I just dont know, could you do a type tutorial?

**Comment by EduardoSepu** [comment]
I already check tutorials

**Comment by EduardoSepu** [comment]
but not with the printer..

**Comment by aleksilassila** [comment]
There's a quick summary of how to use the mod in this github repo's [front page](https://github.com/aleksilassila/litematica-printer#how-to-use)
