### ISSUE TITLE
Wrong blocks placed

### ISSUE THREAD

**Issue by SulpherStaer** [aleksilassila/litematica-printer#36]
I don't quite know how to say this other than 'the printer did it wrong'.

Where there were upside down stairs, it placed deepslate tiles, and where there's flowerpots, it just places whatever is in hand.

Here is the schematic. 
[central_post_office.zip](https://github.com/aleksilassila/litematica-printer/files/7118160/central_post_office.zip)

**Comment by Shrek1222** [comment]
Sorry to ask but when you ran the gradlew batch file did you get a .jar file in the builds folder?

**Comment by SulpherStaer** [comment]
https://github.com/aleksilassila/litematica-printer/releases/tag/v1.8

I didn't build anything myself. I downloaded a release build. (The one for 1.17)

**Comment by Shrek1222** [comment]
Oh, i didnt see that. thank sooooo much, been tryna figure out how to build it for hours lol

**Comment by aleksilassila** [comment]
I've noticed some similar behavior, I'm on it

**Comment by aleksilassila** [comment]
Should be fixed in 2.0
