### ISSUE TITLE
Litematica latest settings unavailable

### ISSUE THREAD

**Issue by Ghozgul** [aleksilassila/litematica-printer#39]
Hey!

First I'd like to say thanks for this fantastic mod, I've been looking for something similar for quite a while. Once we know how the printer behave, it's easy to anticipate some potential issue.

But with the latest build of Litematica (litematica-fabric-1.17.1-0.0.0-dev.20210906.183617), some new options appeared, like saving a schematic with lowercase/underscore on the name (area editor: Home Tundra > schematic name: home_tundra) and it's something I really dislike since it's turned on by default.

So when I have the printer mod loaded, the latest options added disappear from the settings. The lowercase/underscore is still showing but no option to turn it off.

**Comment by aleksilassila** [comment]
Should be fixed in the next update.
