### ISSUE TITLE
Blocks disappearing after chunk unload.

### ISSUE THREAD

**Issue by Kriss-Hietala** [aleksilassila/litematica-printer#41]
Minecraft 1.17.1
Litematica printer 1.17 1.8
delay set to 0.2 range to 6(changed later to 4)
I have a strange bug when I place layers, verify them, everything seems ok. Then relog/move away and when I come back there are blocks missing in every layer. And I need to reverify it and fix.
![2021-10-31_19 13 49](https://user-images.githubusercontent.com/77977701/139596499-83f5be5f-c258-470e-9ff7-bd3587756e64.png)
 
![2021-10-31_19 14 18](https://user-images.githubusercontent.com/77977701/139596503-2d62fc50-275b-4eca-92e3-6b11424c1993.png)
before and after logout. those screenshot are apart by seconds.

**Comment by Kriss-Hietala** [comment]
Looks like lowering the range to 2 blocks fixed that... Damn I've already redone it and reverified 7 times...what a pain...Currently have delay 0,3. Looks like it was the range not the speed that was causing this.

**Comment by DWAA1660** [comment]
had same issue thanks for telling how to fix tho

**Comment by aleksilassila** [comment]
Latest update also tried to address this. Hopefully this won't be much of an issue going forward.
