### ISSUE TITLE
When blocks are not obtainable via creative, the player freezes up and it does not solve until /kill is used or other methods of dying occur

### ISSUE THREAD

**Issue by InsaniteaTV** [aleksilassila/litematica-printer#43]
Hi, on the most recent version as of writing this, when the printer encounters a block it cannot place or obtain via creative, e.g. water or glow berry vines, the player freezes and is unable to move. This could be because of my faster than normal (0.05) printer delay, but i have a feeling it is possibly due to those blocks existing

**Comment by SpwCode** [comment]
it is really trying to place blocks like end portals, water, etc. when in survival.

**Comment by white-devil42** [comment]
i had the same issue but i was not placing any un obtainable blocks,
i just turn the printer on and off a few times and i would get un frozen 
i thought it was because of some other mod i was using

**Comment by aleksilassila** [comment]
Can someone confirm if this is still happening in the latest version of the printer? Also make sure your print interval isn't set to 0 or 1

**Comment by white-devil42** [comment]
> Can someone confirm if this is still happening in the latest version of the printer? Also make sure your print interval isn't set to 0 or 1

i have been using the latest release and there is no issues
