### ISSUE TITLE
Minecraft 1.18 support

### ISSUE THREAD

**Issue by 112batman** [aleksilassila/litematica-printer#45]

**Comment by Kodomatsu** [comment]
+++

**Comment by SeveralPple** [comment]
^^^^

**Comment by SweatyMemer** [comment]
^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by SeveralPple** [comment]
Any of you guys know if theres an idea of when 1.18 support will come?

**Comment by aleksilassila** [comment]
It will come right after I have rewritten the mod to fix some other issues, I'm working on it. I'll try to get it out this week and if not, then this year lol
