### ISSUE TITLE
Can't disable air placement

### ISSUE THREAD

**Issue by TyraVex** [aleksilassila/litematica-printer#47]
There should be an option to disable air placement for servers with anticheats.

https://user-images.githubusercontent.com/34800546/146636292-e76bf312-9465-4cc4-b392-32395718987e.mp4

And an option to use temporary blocks such as dirt to place air located blocks like baritone would simplify so much more the process of building

**Comment by aleksilassila** [comment]
I'll add to my todo

**Comment by aleksilassila** [comment]
Will be fixed in the next update
