### ISSUE TITLE
Add support for Forge

### ISSUE THREAD

**Issue by MoustacheOff** [aleksilassila/litematica-printer#48]
I'm using Litematica on Forge 1.16.5, and I really need the printer. Your fork seems amazing.

Links to the Litematica's Forge test versions: https://masa.dy.fi/tmp/minecraft/mods/misc_test_versions/unsupported_temporary_forge_1.16.5/

**Comment by aleksilassila** [comment]
Might do this in the future, I'll add this to my todo

**Comment by Martin2789** [comment]
Do you have a patreon or paypal to "help" to get this feature done? ;)

**Comment by aleksilassila** [comment]
I appreciate the gesture, but I can't really speed things up right now since I'm in mandatory military service and won't be home for a couple of weeks. I'll do an update after that. For those that know java could contribute through code though.

**Comment by aleksilassila** [comment]
I appreciate the gesture, but I can't really speed things up right now since I'm in mandatory military service and the little spare time I have goes to other features or projects unfortunately. Those that know java could contribute through code though

**Comment by Breadabix** [comment]
I would definitely appreciate this, already used it in 1.18 fabric and its brilliant :)

**Comment by aleksilassila** [comment]
Unfortunately seems a bit out of the scope of the project currently, I don't see when I would have the time to implement this.
