### ISSUE TITLE
Print error on Button Placement

### ISSUE THREAD

**Issue by Johannes7k75** [aleksilassila/litematica-printer#49]
every time the mod places stone buttons i get this error 
java.lang.NoSuchFieldException: yaw
![image](https://user-images.githubusercontent.com/57235955/147255455-a90e7d80-4efe-4383-a4a3-3d8c6c316582.png)

**Comment by aleksilassila** [comment]
Is this latest version of printer and what version of minecraft do you use?

**Comment by Johannes7k75** [comment]
Printer version 2.0 and minecraft version 1.18.1.
The button gets placed but the errors appears

**Comment by aleksilassila** [comment]
If it doesn't crash, this is actually fine. Looking at the code, it's just a console log I've forgot to remove and shouldn't be anything to worry about. I'll remove the logger in next update.
