### ISSUE TITLE
Weird Objects that spawn instead of Blocks when loading a Schematic

### ISSUE THREAD

**Issue by Ereshkigal101** [aleksilassila/litematica-printer#5]
**Minecraft version**
Which Minecraft version are you playing on?
**Minecraft 1.16.4**

**Mod version and malilib version**
Which **exact** mod version are you using? Include the **full** mod file name which includes the build date and time for the development versions, or you can see the mod version in the title of the Litematica main menu.
**Litematica-Fabric-1.16.3-1.6.jar
malibib-fabric.1.16.4.0.10.0-dev.21+arne.3.jar**

**Description of the bug**
**For some reason, every time I load a schematic, it gives me these weird looking objects instead of blocks. Image attached.**

**Context**:
**It was working prior to today, but all of a sudden it's giving me these weird objects. I've tried with and without shaders, nothing changes. Tried deleting my config folder, but to no avail for a fix.**

**Screenshots**
![image](https://user-images.githubusercontent.com/66820531/107871931-09867300-6e74-11eb-8b46-45c16fd86df4.png)

**Comment by rndmbluescreen** [comment]
Hey i had the exact same problem. My Solution was literally what was standing on the official litematica site: disable shaders>restart the game. I was able to activate the shaders without it glitching out again.

**Comment by Ereshkigal101** [comment]
> Hey i had the exact same problem. My Solution was literally what was standing on the official litematica site: disable shaders>restart the game. I was able to activate the shaders without it glitching out again.

Lemme give that a try real quick, I'll let you know if it works <3

**Comment by Ereshkigal101** [comment]
> Hey i had the exact same problem. My Solution was literally what was standing on the official litematica site: disable shaders>restart the game. I was able to activate the shaders without it glitching out again.

... bruh that actually worked lol. Thank you so much!
