### ISSUE TITLE
Observers reversed 

### ISSUE THREAD

**Issue by white-devil42** [aleksilassila/litematica-printer#51]
all the observers are placed in opposite direction
might be just a typo in code as i'm not good at java i dont know where
should be a quick fix
![2022-01-02_19 20 34](https://user-images.githubusercontent.com/61072624/147877923-e98561d0-152b-4b43-9574-fc59c9023b39.png)
![2022-01-02_19 20 25](https://user-images.githubusercontent.com/61072624/147877931-2128efc4-59c2-4f63-9753-3d8ee278b198.png)

**Comment by white-devil42** [comment]
![image](https://user-images.githubusercontent.com/61072624/147878085-2c1fb354-0848-4779-b986-37def9d88ea9.png)

this might be it
https://github.com/aleksilassila/litematica-printer/blob/printing/src/main/java/me/aleksilassila/litematica/printer/printer/PrinterUtils.java

**Comment by mustafa383** [comment]
https://user-images.githubusercontent.com/57295889/147880068-1f0f18c0-bb12-4394-a454-16abb8e46b65.mp4

same problem

**Comment by white-devil42** [comment]
[litematica-printer-1.18.1-2.1.jar.zip](https://github.com/aleksilassila/litematica-printer/files/7799274/litematica-printer-1.18.1-2.1.jar.zip)
(fix, maybe)

can some one test this i cant do it now my dad is right behind me

**Comment by mustafa383** [comment]
> 

not working

**Comment by white-devil42** [comment]
ok :(

**Comment by aleksilassila** [comment]
I'll fix it

**Comment by MrPryor** [comment]
Any eta on fix? :)

**Comment by aleksilassila** [comment]
Here's a fixed build for 1.18, I'll add the fix in the next release also once I get that done: [litematica-printer-1.18.1-2.1.zip](https://github.com/aleksilassila/litematica-printer/files/7821274/litematica-printer-1.18.1-2.1.zip)
Or you can build from source

**Comment by MrPryor** [comment]
Ty! Much appreciated.

**Comment by zhaixianyu** [comment]
https://github.com/aleksilassila/litematica-printer/blob/printing/src/main/java/me/aleksilassila/litematica/printer/printer/PlacementGuide.java

![image](https://user-images.githubusercontent.com/60321485/156842999-b8983921-0fb5-4334-ae2a-db5f7aa9a4dd.png)

**Comment by aleksilassila** [comment]
Will try to get the next version out this week

**Comment by reman8683** [comment]
Ok, Thanks!!! :]

2022년 3월 5일 (토) 오후 2:04, Aleksi Lassila ***@***.***>님이 작성:
