### ISSUE TITLE
[BUG] Crash when joining World

### ISSUE THREAD

**Issue by ForBai** [aleksilassila/litematica-printer#54]
Every time i join a world game crashes

Crash Log:
https://paste.ee/p/7o5m5

**Comment by ppmaster69** [comment]
sucks 2 be you XD

**Comment by aleksilassila** [comment]
Here's a list of things to check
 - Does the minecraft crash without litematica-printer?
 - Do you have latest versions of the printer, litematica, malilib and fabric api?
 - Does the game crash when using the vanilla launcher?
 - Does the game crash when you disable all the other mods apart from the printer, litematica, malilib and fabric api?

Let me know here if you run any further tests

**Comment by aleksilassila** [comment]
Reopen if the issue persists
