### ISSUE TITLE
Auto Right Click is bugged in multiplayer

### ISSUE THREAD

**Issue by ruigouveiamaciel** [aleksilassila/litematica-printer#56]
Hello

While testing the mod in a multiplayer server that isn't running at 20 TPS constantly I noticed somethings.

1. The auto right click feature (to set repeater delays for example) doesn't work very well in multiplayer. I think the auto right click clicks once every tick but if the server isn't running at 20 TPS what happens is the printer clicks twice in the repeater and completely skips the correct delay state. It would be nice to have a config setting to change the delay from 1 tick to something else. Or it could just use the same delay for placing blocks.
2. Printer breaks when there's a powered redstone component on the schematic, it keeps right clicking the repeater for example but because it will never be powered (because the redstone behind the repeater hasn't been built yet) it keeps right clicking the repeater forever. It would be nice for redstone components to ignore the powered state. The only exception to the powered state should be levers, I think.

**Comment by aleksilassila** [comment]
I fixed this once but not sure if I included the fix in the rewrite I did for the latest version :D Reopen if this is still an issue.
