### ISSUE TITLE
Incorrect blocks placed and some blocks don't place.

### ISSUE THREAD

**Issue by charliegustard** [aleksilassila/litematica-printer#58]
Hi,
Firstly, Thankyou for developing this mod, without it my satisfying style of time lapses wouldn't be possible! https://youtu.be/2gta_U957mg

Overall this mod has worked great and achieved what I've needed since the last update. However, being a frequent user of this mod I have come across various issues in 1.17 (with the latest version of litematica-printer)
Listed below are the issues:

Incorrect blocks placed:
This is pretty self explanatory, It's fairly uncommon for this to happen but it does occasionally happen. Another block in your inventory will be placed instead of what the block in the schematic is meant to be. These blocks are highlighted red. I'm assuming it's highlighted red just because the litematica mod recognises that the blocks shouldn't be in the schematic.

Pots with flowers in and and un-activated vertical iron trap doors won't place:
Also self explanatory about the pots with flowers in but as for the un-activated vertical trap doors..
well, most commonly us builders will use the debug stick to set trap doors to be vertical without the need for redstone (which would activate it, making it vertical). These vertical iron trap doors that aren't activated by redstone don't place. 

Signs ask you to type on them:
I'm not sure if this is actually an issue or not but in my situations it can be a little inconvenient. Signs require you to type onto them or hit "done" this can be annoying when you've just used signs to make furniture or a fancy roof architrave for example. maybe there should be an option to edit or skip having to input an action every time a sign is placed.

I hope you can improve on the mod by resolving these issues.
Again, thankyou for developing this mod, it improves the quality of my work as a builder and content creator and I greatly appreciate it.

**Comment by aleksilassila** [comment]
Hey @charliegustard 

Firstly, sorry I forgot to reply to this. Secondly, all of these should be resolved in the latest version (3.0). It's been a while but hope it helps if you are still using this for the videos (which are really cool btw). If you still encounter incorrectly placed blocks, could you create a new issue or contact me on discord and letting me know what blocks are placed incorrectly. Also providing the incorrectly printed schematic or a screenshot would help, if you can provide those.

Cheers!

**Comment by DereC4** [comment]
Agreed. Trapdoors (iron and wood) will duplicate place, and iron trapdoors especially are not reliably printable. Same with walls.

#286 

Citing:
https://www.reddit.com/r/litematica/comments/1r1n1lu/litematica_bug_iron_trapdoors_place_twice/
https://www.reddit.com/r/ModdedMinecraft/comments/1rulewj/litematica_printer_tip_when_dealing_with/
