### ISSUE TITLE
Cant place lava buckets

### ISSUE THREAD

**Issue by Legomonster33** [aleksilassila/litematica-printer#61]
attempting to print a schematic of lava doesnt work

**Comment by aleksilassila** [comment]
For now that's intentional, since flowing liquids could be placed before their container is done and ruin parts of the structure.

**Comment by Legomonster33** [comment]
> For now that's intentional, since flowing liquids could be placed before their container is done and ruin parts of the structure.

Fair enough, although a config would be nice
