### ISSUE TITLE
Ender chest / autocraft

### ISSUE THREAD

**Issue by beldinn** [aleksilassila/litematica-printer#64]
**greetings**

I use the printer on a german multiplayer Server with the ender chest mod.

My question is; is it possible to add a Feature wich grands litematica the permission to pick blocks/Stacks automatic out of the ender chest?
The ender chest plugin works like: tipe /ec and your Personal ender chest will open.
This would help a lot, because its like expanding your inventory.
Perfect would be if theres an option to Set a delay for this, i dont want to get kicked because of too many packages.

Second question;
Is it possible to add a auto craft Option for Blocks like: planks, stairs, Walls, slabs etc?

Thank you 😇

**Comment by aleksilassila** [comment]
Due to lack of time I deem this out of scope of the project.
