### ISSUE TITLE
Noteblocks not setting

### ISSUE THREAD

**Issue by CypherCrafting** [aleksilassila/litematica-printer#65]
Noteblocks don't automatically get set to the right notes

**Comment by BloodyNoah** [comment]
Im pretty sure, that litemetica doesnt consider the noteblock notes when creating a litemetica. So this is probably an issue of litemetica.

**Comment by DonFlymoor** [comment]
litemetica does, if the note is wrong litematica tells you.

**Comment by BloodyNoah** [comment]
Well this is not a feature of the printer then. It was just not programmed to click on the noteblocks

**Comment by aleksilassila** [comment]
Let me know if this issue persists in 3.0
