### ISSUE TITLE
Paths & Farmland Will not be made.

### ISSUE THREAD

**Issue by Manrock1** [aleksilassila/litematica-printer#66]
Working on converting my mushroom island to grass and this seems like one of the best helps! Just need it to recognize when to use a shovel/hoe instead of solid block!

**Comment by aleksilassila** [comment]
I'm working on it :)

**Comment by Manrock1** [comment]
> I'm working on it :)

Awesome! Dunno how it would work but would be handy to stop using a specific shovel at 1 durability left! or like 10 to be safe.

**Comment by aleksilassila** [comment]
They will now in 3.0
