### ISSUE TITLE
Printer "Breaks" Players' Neck, Can't Place Anything

### ISSUE THREAD

**Issue by porplenugget** [aleksilassila/litematica-printer#68]
Using the printer for a pumpkin farm, after about 2/3 of it is placed, blocks stop placing.  Looking at my character from another account, my head is pointed straight up.  Leaving printer mode, I cannot place any other blocks (assuming because server thinks I am looking away from where I try to place).  The only way to unstick the head is to fully exit MC and rejoin the server. 

Edit:  It seems to replicate this issue, it comes from placing the pistons face down from above.  Going into a single player world and using the printer will unstick the head.  I did observers by themselves and there is no issue, when I try to place the pistons again with the printer, the head gets stuck.

Screenshots of progress before breaking and "broken" character below:

![2022-02-23_16 08 12](https://user-images.githubusercontent.com/100317944/155408924-78426b68-57a6-4372-a5f7-031d640d278e.png)
![2022-02-23_16 06 15](https://user-images.githubusercontent.com/100317944/155408927-6779f8f2-47ea-4375-87a3-a4bf56d0b14d.png)
![2022-02-23_16 06 07](https://user-images.githubusercontent.com/100317944/155408929-7f836a56-a2ab-4847-b989-1b85dee23baf.png)

**Comment by aleksilassila** [comment]
Brutal. Let me know if this persists in v3.0.
