### ISSUE TITLE
make compatibility with easy place mode [suggestion]

### ISSUE THREAD

**Issue by ppmaster69** [aleksilassila/litematica-printer#7]
this would allow you to build in mid air and not need to place a block in middle of air just to get the pritner going

**Comment by aleksilassila** [comment]
I’ll have to look into this, but the base line is that you cannot place a block midair without any support without commands. So there would have to be a support structure of some sort. Keep in mind that the mod has to work on multilayer servers without /setblock command. Did you have more specific example as to how it should work?

**Comment by ppmaster69** [comment]
umm give me 20 minutes to make a video there is a mod within litematica that allows you to place blocks in middle of air

**Comment by ppmaster69** [comment]
https://youtu.be/X3Uc_1YlIv4

**Comment by aleksilassila** [comment]
I see, I can try to make it work next week. I assume that doesn't work in multiplayer though right? Without commands at least

**Comment by ppmaster69** [comment]
it does work in multiplayer i used it on 5 server and worked on all
and yet to be banned so i asume its completly allright

**Comment by frogbootz** [comment]
Just wanted to add that i agree with this change so much as mid air block placement would make this 100 times better, thank you for the mod though it has been a life saver!

**Comment by Declipsonator** [comment]
Air placement checks were removed in 1.13+ :wink:

**Comment by basvlier** [comment]
how to use this printer where do I need to put this fiile? pls helpp

**Comment by ppmaster69** [comment]
any updates to progress?

**Comment by jiaho3388** [comment]
So placing blocks in mid-air with printer still doesn't work like in servers or so?

**Comment by jiaho3388** [comment]
I'm also waiting for this. If you can make this work, it would be excellent. Thx a lot.

**Comment by aleksilassila** [comment]
I haven't forgotten this, just have a lot of stuff and little time =)

**Comment by jiaho3388** [comment]
oh, ha. Actually, English is not my First language. Don't know if I can describe things clearly :P. So, umm. Just want to say thank you for your hard-work. Keep up! And,um,Don't forget to like have some rest if you're tired. Just ..Never stress yourself out. It's must be difficult or like a lot of problems waiting to be solved. ALL the best! REALLY appreciate your projects!❤️
