### ISSUE TITLE
The perfect addon, thanks! When 1.18.2?

### ISSUE THREAD

**Issue by terrormaximaal** [aleksilassila/litematica-printer#70]

**Comment by aleksilassila** [comment]
Soon™️, hopefully this week

**Comment by terrormaximaal** [comment]
Do you have any update on progress for us?

**Comment by Boobies** [comment]
The commit log is public. No need to annoy the maintainer, especially since this is chit-chat rather than bug reporting.

**Comment by aleksilassila** [comment]
1.18.2 work-in-progress pre-release out
