### ISSUE TITLE
Iron Trap doors won't place open

### ISSUE THREAD

**Issue by charliegustard** [aleksilassila/litematica-printer#75]
![2022-03-22_20 46 04](https://user-images.githubusercontent.com/18568338/159459489-f51f7cb8-8533-43c1-89b8-c5bf1ab14e6c.png)
As seen by the image, the build has open (vertical) iron trapdoors (this is done using the debug stick so redstone isn't needed) Unfortunately with litematica printer, the iron trap doors won't be placed open. only closed.

**Comment by Boobies** [comment]
This isn't a bug. Printing is not like pasting a schematic. It simply has the player place blocks. And there is no way for players to place blocks like that.

**Comment by charliegustard** [comment]
> This isn't a bug. Printing is not like pasting a schematic. It simply has the player place blocks. And there is no way for players to place blocks like that. (Unless they are in Creative and use a debug stick, I suppose, but then they could simply paste the schematic to begin with.)
by saying: "they could simply paste the schematic to begin with" you are making false assumptions about what people may use this mod for. In my case, I use it as a timelapse tool.
I understand why you would say this isn't a bug. However the developer did mention on the release page: _"Should you come across any blocks that are placed incorrectly and are not mentioned in above blacklist of blocks, a crash or some kind of other unwanted behavior on the printer's side, please create an issue and I'll have a look."_ Based on the schematic, the trapdoors are placed incorrectly, so I submitted an issue as requested. It's up to the developer if they think it's a bug and if want to do anything about it.

**Comment by Boobies** [comment]
It's not up to the developer, it's not possible to implement this in a way that would work in vanilla Survival.

**Comment by aleksilassila** [comment]
As far as I know, there is no way of placing trapdoors that way without commands in vanilla. Because the printer is designed to work on servers without admin powers, I'd say implementing this would be out of scope of the project, not to mention time consuming also. Sorry!

**Comment by DereC4** [comment]
Agreed. Trapdoors (iron and wood) will duplicate place, and iron trapdoors especially are not reliably printable. Same with walls.

https://github.com/aleksilassila/litematica-printer/issues/286

Citing:
https://www.reddit.com/r/litematica/comments/1r1n1lu/litematica_bug_iron_trapdoors_place_twice/
https://www.reddit.com/r/ModdedMinecraft/comments/1rulewj/litematica_printer_tip_when_dealing_with/
