### ISSUE TITLE
Printer Does Not Work On Factions Servers

### ISSUE THREAD

**Issue by Cater-Piller** [aleksilassila/litematica-printer#76]
Hello Aleksi!

Your printer plugin is fantastic! I love the overall product and integration. However, in its currant state, for my uses, it is completely unusable. Let me explain. I play Minecraft factions. Specifically, I am a Minecraft factions cannoneer. I design tnt cannons purposed to raid large bases in Minecraft faction servers. Schematica is the standard mod chosen by cannoneers to print these cannons in-game, and raid an enemy base. A quick google search for "Minecraft factions cannon schematic" will reveal exactly what I am referring too. The intricacy and scale of these cannons pretty much necessitates schematica's printer capability. However, schematica is limited to 1.12 and below, so it is impossible to use in conjunction with any fabric 1.18 mods. This has limited faction cannoneers to these early versions of Minecraft for many years. Finally your plugin appears to solve this problem, if not for its shortcomings.  

This context is necessary to understand my problem with your plugin in its currant state. Your plugin does something very similar to schematica's printing function, however, it is fundamentally different. Firstly, your plugin places blocks one at time, which is much slower than schematica's printing mode. Schematica has settings which allow you to print in a set area size (eg. 3 block radius). I anticipate that your plugin does not have the capability to do this because the method by which your plugin places blocks is different than schematica's method. 

This brings me to my biggest problem. The previous stated differences are not huge difficulties, just rather inconvenient. The biggest problem its that your printer function does not place blocks in factions servers at all, where schematica does. I anticipate that this is due to the something server-side, perhaps an anti-cheat detecting the unusual method of block placement which your printer uses. This would further confirm my theory that your plugin uses a different method of placing blocks than schematica does. I have absolutely no idea what to look for in your code, as I have checked briefly. I am requesting that you make your plugin compatible with Minecraft factions servers, to make it a viable alternative to schematica. If this became possible, I think that your plugin would quickly the primary mod in the mod folder of a factions cannoneer, as being the only alternative to schematica for 1.18 fabric users.

I am sure that the nature of this problem is very fundamental to your plugin, and perhaps my concerns are are a bit confusing. If you would like to talk to me on discord for further insight, please add me: Cater-Pillar#3595. Furthermore, I would be happy to commission you to complete this project, as I would be extremely excited to see a working cannon printer on 1.18 fabric.

Thanks,
Cater

Server IP: play.pika-network.net

https://user-images.githubusercontent.com/102250577/159810348-24aa9ea9-6ac0-414b-bedc-56bd4b328fe2.mp4

**Comment by aleksilassila** [comment]
Hi,

I appreciate the feedback. Could you specify, which printer version did you use when running into these issues? It is most likely the anti-cheat that is messing with the placements. 

Also if you still haven't tried the latest experimental version (2.2) of the printer, give it a try and let me know if you are able to print in your server. Just remember to toggle off printInAir option. I've recently focused on making the printing seem more legitimate server-side to counter anti-cheat, so hopefully that will resolve the issue. 

Cheers!

**Comment by Cater-Piller** [comment]
Hello!

Thank you for the swift reply. I was using your 2.1 version. I am now trying out your 2.2 version, but it currently seems to be have a number of different problems. The printair option is really helpful, and I think that it, perhaps, solves one of the problems. However, currently when I run the printer on the factions servers, it acts as if it is doing absolutely nothing. It doesn't even give a placing block animation. I know that this is not a settings issue because the exact same settings work in single player. Another weird bug: whenever I try to use the printer feature in a factions server, and it doesn't work, if I switch over to single player, it no longer works in single player either. It is as if the factions servers break the printer plugin entirely, so that it no longer works in single player either. The only way to fix the bug is to restart Minecraft.

Again, if you would like more details, I am sure I could better articulate them on discord: Cater-Pillar#3595. Thanks for all of your work. I am using Litematica-fabric-1.18.2-0.11.1 and Litematica-printer-1.18.2-2.2

**Comment by Cater-Piller** [comment]
Do you think that there will be a solution to this problem?

**Comment by aleksilassila** [comment]
Yeah I do, will try to get next stable update out next week. I haven't tested 2.2 on servers myself, so it doesn't surprise me that something is broken there. Probably will be an easy fix once I have the time to look into it. Stay tuned 👍

**Comment by aleksilassila** [comment]
Everything should be fixed in the next update (latest commit), fingers crossed. Reopen if you still notice issues after I update in about a week from now.
