### ISSUE TITLE
Incorrect block orientation on spigot servers

### ISSUE THREAD

**Issue by tubbyflumpkins** [aleksilassila/litematica-printer#79]
Hello, I'm using version 2.1 on a 1.18.1 spigot server.  All the blocks get placed just fine but they all face the direction that the player is facing resulting in many incorrect orientations.  Schematica had a feature to counteract this where it wouldn't place a block until the player was facing the correct orientation. 

This is the same bug as the built in easy place mode for litematica. Unusable on servers.

**Comment by aleksilassila** [comment]
Reopen this if the issue persists on latest on 2.3 that I'm about to release soon.
