### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Tokaroi** [aleksilassila/litematica-printer#8]
Hi
how do i use the printer function?
is there a video i can watch to help me find it and use it?

Thanks

**Comment by aleksilassila** [comment]
No video currently, but it should be quite straight forward. First, make sure you have only the printer mod installed (not both original litematica and printer). After that there should be a new keybind in keybinds section for enabling and disabling printer ("O" by default if I remember correctly). Additionally there's some printer settings added in the settings page (range, speed).

**Comment by basvlier** [comment]
so If im correct I just need to put printer in my mods folder en not litematica

**Comment by basvlier** [comment]
and does ik work whit paper

**Comment by aleksilassila** [comment]
Yep, in mods folder. If you are unsure how to install mods and/or fabric, check out how to install the original litematica mod first.

Paper is for server sided mods (plugins) and has nothing to do with this mod. So you can use this on any server.

**Comment by FredTheFriendlyFox** [comment]
what settings make it place faster
