### ISSUE TITLE
observers not facing properly on fabric servers

### ISSUE THREAD

**Issue by neilhuang007** [aleksilassila/litematica-printer#81]
the ob servers are place opposite sided or where the player is facing, although you tried to fix this in 2.1, but it still didn't work and the mode are the newest version, my game version is 1.16.5 fabric.

**Comment by Johannes7k75** [comment]
Same for me on 1.18.2

**Comment by aleksilassila** [comment]
Fixed this in the latest commit and will do an update in the near future
