### ISSUE TITLE
Printing doesn't seem to work at all despite the fact that the mode is enabled.

### ISSUE THREAD

**Issue by FrozenDragon0** [aleksilassila/litematica-printer#87]
Hey there! So whenever I turn on the printing mode It doesn't seem to want to work at all and V doesn't do anything either, I made this to ask why might this be? Perhaps I'm doing something wrong? 

EDIT: Yes I have the resources in Survival for the schematic that requires them, and the mode didn't want to work in creative either.

**Comment by aleksilassila** [comment]
This is the case in the latest experimental version and is only an issue on multiplayer servers apparently. I will update the mod in a couple of days to fix this.

**Comment by FrozenDragon0** [comment]
It's not just servers, it affects Solo worlds aswell.

**Comment by FrozenDragon0** [comment]
As a temporary solution I've switched back to version 2.1 of the mod.

**Comment by aleksilassila** [comment]
2.3 out
