### ISSUE TITLE
Works in solo but not on server?

### ISSUE THREAD

**Issue by btainge44** [aleksilassila/litematica-printer#89]
If there is some sort plugin or its disabled on some servers then sorry for opening this. I can the printer to work just fine in a solo world (creative and survival) but I cannot get it to work on a server. The server I'm playing on is play.newearth.gg.

**Comment by aleksilassila** [comment]
What version are you using and have you tested if it works on other servers? How isn't it working? Have you tried turning off placeInAir option if there's some sort of anti-cheat?

**Comment by aleksilassila** [comment]
Double check that you have 2.3 version, this sounds like 2.2

**Comment by luiswenger** [comment]
I'm having the same issue. Also on version 2.3. playing on a paper server

**Comment by O5-0** [comment]
Me too, but the Litematica printer version 1.18.1-2.1 works normally on the paper server

**Comment by btainge44** [comment]
I double-checked and I am using v2.3. Should I use an older version?

**Comment by FurnyGo** [comment]
same on 2.2 2.3

**Comment by jetblackrx89** [comment]
Same issue as well. Using the latest 2.3, confirmed printing works fine in a single player creative map but not in SMP creative.

**Comment by aleksilassila** [comment]
Please let me know if this still occurs in 2.4. There was some weirdness in 2.3 where it'd work on some servers but bungeecord/teleports seemed to mess with things.

**Comment by tcortega** [comment]
@aleksilassila It is still happening for me in a specific server I'm at. Owner says it is some sort of plugin that he has and that disables the printer.
