### ISSUE TITLE
Does not print underwater

### ISSUE THREAD

**Issue by LegendLeaks** [aleksilassila/litematica-printer#9]
Hi im trying to use this printer for an underwater build but I noticed that there has to be an air block for the printer to actually place the block, it does not print the blocks if there is water. Could you please fix this? It would be really helpful. Version 1.16.5

**Comment by basvlier** [comment]
hey man how do I use this printer where do I need to put this file? pls help me out

**Comment by aleksilassila** [comment]
Will be fixed in next patch
