### ISSUE TITLE
When I join a world litematica doesnt works

### ISSUE THREAD

**Issue by gigel1948** [aleksilassila/litematica-printer#99]
I tried another version but older, still doesnt work
It doesnt crash, but it doesnt load ( litematica)

**Comment by aleksilassila** [comment]
Could you provide some more details? For example, do you see the mod settings in the bottom of litematica's settings? What version of the game and mod you're using?

**Comment by gigel1948** [comment]
Okay, I dont see litematica when I press f3 and when I press M nothing happens.
If u want, come Discord

**Comment by aleksilassila** [comment]
If that's the case, then it has something to do with your fabric setup / litematica. Follow their instructions to get litematica working first, and then add the printer into the equation. Note that the printer requires you to also install litematica and it's dependencies.
